[package]
name = "sensulator"
version = "0.4.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
repository = "https://github.com/tstellanova/sensulator"
edition = "2018"

[dependencies]
rand = "0.6.5"

[dev-dependencies]
quickcheck = "0.6"

